# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5aa891febf05fcb1c63713260fd0fd39995628c7f3e7ba10a1c51d21bf8b7a5267841322174e1aca92c133b2ab28fae37b8dd1f2004ce2b10e1b6c0407e6147

test:
  secret_key_base: 6c942fb4aebaab53c78f9906904a1875a6b52e4d0765e07b52ed89a7acf8b584d7989144b4ed11906d87124a6d496217491d946b1778f97b0330a1acbefa164e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
